### ISSUE TITLE
ncd::mainQueue().dispatch  got assertion failed on version 0.0.6

### ISSUE THREAD

**Issue by vvhh2002** [agnat/ncd#1]
Hi, thanks you works.

I use ncd 0.0.6 ncd::mainQueue().dispatch  with Nan::AsyncWorker like this:

```
class PiWorker : public Nan::AsyncWorker {
public:
    PiWorker(Nan::Callback *callback, int atimes,ncd::AsyncEventEmitter * aemitter)
            : AsyncWorker(callback),  times(atimes),
             emitter(aemitter) {}
    ~PiWorker() override{}

    // Executed inside the worker-thread.
    // It is not safe to access V8, or V8 data structures
    // here, so everything we need for input and output
    // should go on `this`.
    void Execute () override {
        for (int i = 0; i < times; ++i) {
              ncd::mainQueue().dispatch([=](){
                    emitter->emit("log", "test in async threads");
              });
            usleep(100000);
        }
    }

    // Executed when the async work is complete
    // this function will be run inside the main event loop
    // so it is safe to use V8 again
    void HandleOKCallback () override {
        Nan::HandleScope scope;

        v8::Local<v8::Value> argv[] = {};

        callback->Call(0, argv, async_resource);
    }
private:
    int times;
    std::shared_ptr<ncd::AsyncEventEmitter>  emitter
};
```

I got a assert:
```Assertion failed: (queue != nullptr), function mainQueue, file /node/node_modules/ncd/include/ncd/queue_getters.hpp, line 26.```

If I changed mainQueue to defaultQueue , It can works.

**Comment by agnat** [comment]
Hi,

> Hi, thanks you works.

Thank you. Please note that this is just a toy. I don't actively work on it. That said, enjoy playing with it.

The library is not designed to work with `AsyncWorker`, it is designed to replace it. You have to use `dispatch(...)` on some ncd work queue to get a valid main queue handle... IIRC.

Maybe just start with the first example, make sure it still compiles and go from there. Like I said, it's kind of unmaintained.

**Comment by vvhh2002** [comment]
thanks,
I see
